# Day 2 - Data handling in Python with NumPy

Welcome to the second day of the Training ,Lets get our hands dirty with NumPy ie Numerical Python.

This liberary of Python is generally used for careating N dimensional array ,and perform various operations such as Shaping,Manipulating it.

In [2]:
import numpy as np

In [7]:
mylist = [1,2,4,3]

In [8]:
mylist

[1, 2, 4, 3]

Lets convert it into Numpy array

In [11]:
myarray = np.array(mylist)

In [12]:
myarray

array([1, 2, 4, 3])

In [13]:
mylist2 = [11,22,44,33]

In [15]:
myarray2 = np.array(mylist2)

In [16]:
myarray2

array([11, 22, 44, 33])

In [18]:
mylists=[mylist,mylist2]

In [20]:
mylists

[[1, 2, 4, 3], [11, 22, 44, 33]]

In [21]:
myarrays = [myarray,myarray2]

In [22]:
myarrays

[array([1, 2, 4, 3]), array([11, 22, 44, 33])]

In [23]:
myarr = np.array(mylists)

In [24]:
myarr

array([[ 1,  2,  4,  3],
       [11, 22, 44, 33]])

This was the example of Multidimensional array here 2D

In [26]:
myarr.shape

(2, 4)

In [27]:
myarr.dtype

dtype('int64')

In [28]:
#Making special type of arrays

In [36]:
#zeros
np.zeros(5) 

array([ 0.,  0.,  0.,  0.,  0.])

In [37]:
#ones
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

In [38]:
np.zeros((2,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [39]:
np.ones((5,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [48]:
np.empty((5))

array([ 0.,  0.,  0.,  0.,  0.])

In [47]:
np.empty([2,2],dtype=int)

array([[0, 0],
       [0, 0]])

In [52]:
np.empty((3,3),dtype=tuple)

array([[None, None, None],
       [None, None, None],
       [None, None, None]], dtype=object)

In [54]:
#Identity array
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [58]:
np.arange(5) #This is similar to range ,Since its giving array there for 'a-range'

array([0, 1, 2, 3, 4])

In [59]:
5/2

2

In [60]:
#Takes care of floats
from __future__ import division

In [61]:
5/2

2.5

In [62]:
# Create array
arr1 = np.array([[1,2,3],[8,9,10]])

#Show
arr1

array([[ 1,  2,  3],
       [ 8,  9, 10]])

In [63]:
#Multiplying Arrays
arr1*arr1

array([[  1,   4,   9],
       [ 64,  81, 100]])

In [64]:
#Subtraction
arr1-arr1

array([[0, 0, 0],
       [0, 0, 0]])

In [65]:
#Arithmetic operations with scalars on array
1 / arr1

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.125     ,  0.11111111,  0.1       ]])

In [66]:
#Exponential operation
arr1 ** 3

array([[   1,    8,   27],
       [ 512,  729, 1000]])

In [67]:
#Creating sample array
arr = np.arange(0,11)

In [69]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [70]:
#Get a value at an index
arr[8]

8

In [71]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [72]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

In [73]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [83]:
# Reset array, we'll see why i had to reset in  a moment
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Concept of Slicing

In [84]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr




array([0, 1, 2, 3, 4, 5])

In [85]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr


array([99, 99, 99, 99, 99, 99])

In [86]:
# Now note the changes also occur in our original array!
arr

# Data is not copied, it's a view of the original array! This avoids memory problems!



array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [87]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [90]:
# Indexing a 2D array

arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [91]:
#Indexing row
arr_2d[1]


array([20, 25, 30])

In [92]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]


20

In [93]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [94]:
#Shape bottom row
arr_2d[2]


array([35, 40, 45])

In [95]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

In [96]:
# Fancy Indexing

#Set up matrix
arr2d = np.zeros((10,10))

In [97]:
arr2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [98]:
#Length of array
arr_length = arr2d.shape[1]

In [99]:
arr_length

10

In [100]:
for i in range(arr_length):
    arr2d[i]=i

In [101]:
arr2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.]])

In [102]:
#Fancy indexing allows the following
arr2d[[2,4,6,8]]

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.]])

In [109]:
#Fancy indexing allows the following 
arr2d[[2,4]]

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.]])

**Observe the difference is due to double square brackets.**

In [110]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.]])

In [111]:
#Create array
arr = np.arange(50).reshape((10,5))

#Show
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [112]:
#Lets transpose
arr.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]])

In [113]:
# Taking dot product of matrices
np.dot(arr.T,arr)

array([[7125, 7350, 7575, 7800, 8025],
       [7350, 7585, 7820, 8055, 8290],
       [7575, 7820, 8065, 8310, 8555],
       [7800, 8055, 8310, 8565, 8820],
       [8025, 8290, 8555, 8820, 9085]])

In [114]:
# For 3D matrix
arr3d = np.arange(50).reshape((5,5,2))

#Show
arr3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])

In [115]:
#We can also transpose a 3d matrix

arr3d.transpose((1,0,2))

array([[[ 0,  1],
        [10, 11],
        [20, 21],
        [30, 31],
        [40, 41]],

       [[ 2,  3],
        [12, 13],
        [22, 23],
        [32, 33],
        [42, 43]],

       [[ 4,  5],
        [14, 15],
        [24, 25],
        [34, 35],
        [44, 45]],

       [[ 6,  7],
        [16, 17],
        [26, 27],
        [36, 37],
        [46, 47]],

       [[ 8,  9],
        [18, 19],
        [28, 29],
        [38, 39],
        [48, 49]]])

In [116]:
# If you need to get more specific use swapaxes
arr = np.array([[1,2,3]])

#Show 
arr

array([[1, 2, 3]])

In [117]:
arr.swapaxes(0,1)

array([[1],
       [2],
       [3]])

In [118]:
arr = np.arange(11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [119]:
#Taking Square Roots
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [120]:
#Calcualting exponential (e^)
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [121]:
# Binary Functions require two arrays

#Random array (normal dist)
A = np.random.randn(10)

A


array([-0.28068864, -0.07746706,  0.39328893,  0.00275613, -0.27897644,
        0.65171338,  0.72690429,  0.56875275,  1.04626094,  0.18996117])

In [122]:
#Random array (normal dist)
B = np.random.randn(10)
B

array([-0.03318384, -0.10673559, -0.30717107,  2.2249489 ,  0.70347233,
        0.04208589,  0.34062548, -0.31047279,  1.07061759,  0.97326676])

In [123]:
#Addition
np.add(A,B)

array([-0.31387248, -0.18420266,  0.08611786,  2.22770503,  0.42449589,
        0.69379927,  1.06752977,  0.25827996,  2.11687853,  1.16322793])

In [124]:
#Finding max or min between two arrays
np.maximum(A,B)

array([-0.03318384, -0.07746706,  0.39328893,  2.2249489 ,  0.70347233,
        0.65171338,  0.72690429,  0.56875275,  1.07061759,  0.97326676])

In [125]:
#For full and extensive list of all universal functions
website = "http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs"
import webbrowser
webbrowser.open(website)

True

In [1]:
#Lets learn how to use the numpy where

In [3]:
A = np.array([1,2,3,4])

B= np.array([100,200,300,400])

In [5]:
Condition= np.array([True,True,False,False])

In [8]:
answer = np.where(Condition,A,B)

In [9]:
answer

array([  1,   2, 300, 400])

where can be used for 2D manipulation also.

In [11]:
a =np.array([[1,2],[3,4]])

In [12]:
b =np.array([[4,3],[2,1]])

In [13]:
c=np.array([[True,True],[False,False]])

In [14]:
r=np.where(c,a,b)

In [15]:
r

array([[1, 2],
       [2, 1]])

In [21]:
from numpy.random import rand

In [27]:
rr = rand(2)

In [23]:
rr

array([ 0.74291177,  0.02223899])

In [24]:
rr1 = randn(2)

In [25]:
rr1

array([-0.59111761, -1.00025505])

In [33]:
from numpy.random import randint

In [34]:
rr2 = randint(1,100,size=10)

In [35]:
rr2

array([53,  2, 80,  2, 34, 33,  7, 93, 44, 31])

In [36]:
#Other Statistical Processing
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
arr.mean()

5.0

In [41]:
arr.sum()

45

In [44]:
arr.sum(0)

array([12, 15, 18])

In [45]:
arr.sum(1)

array([ 6, 15, 24])

In [42]:
arr.std()

2.5819888974716112

In [46]:
arr.var()

6.666666666666667

In [47]:
#Also any and all for processing boolean arrays

bool_arr = np.array([True,False,True])

#For any True
bool_arr.any()

True

In [48]:
# For all True
bool_arr.all()

False

In [49]:
# Finally sort array

#Create a random array
arr = randn(5)
#show
arr

array([ 0.60410102, -1.89299705,  0.36671444, -1.89306192,  1.13821759])

In [50]:
#Sort it
arr.sort()
#show
arr

array([-1.89306192, -1.89299705,  0.36671444,  0.60410102,  1.13821759])

In [51]:
#Lets learn about unique
countries = np.array(['France', 'Germany', 'USA', 'Russia','USA','Mexico','Germany'])

np.unique(countries)

array(['France', 'Germany', 'Mexico', 'Russia', 'USA'], 
      dtype='|S7')

In [52]:
arr = np.arange(5)

In [53]:
#Saving array on disk in binary format (file extension .npy)
np.save('my_array',arr)

In [54]:
#Change arr
arr = np.arange(10)
#Show
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
#Lets see the original saved copy
np.load('my_array.npy')

array([0, 1, 2, 3, 4])

In [56]:
#Saving multiple arrays into a zip file
np.savez('two_arrays.npz',x=arr,y=arr)

In [57]:
#Now loading multiple arrays
archive_array = np.load('two_arrays.npz')

#Show
archive_array['x']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
archive_array['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
#Now saving and loading text files

arr = np.array([[1,2,3],[4,5,6]])
np.savetxt('my_test_text.txt',arr,delimiter=',')

In [61]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
arr = np.loadtxt('my_test_text.txt',delimiter = ',')
arr


array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])